DevHireExtended/DevHireBot/urls.py
from django.urls import path, include
from django.contrib.auth.decorators import login_required
from django.contrib.auth import views as auth_views
from . import views
from . import api_views
from .customDecorators import anonymous_required

app_name = "DevHireBot"

urlpatterns = [
    path("", views.index, name="index"),
    
    # Interview related views
    path("get_resume/", views.get_resume, name='get_resume'),
    path("interview_pilot/", views.interview_pilot, name='interview_pilot'),
    path("interview_bot/", views.interview_bot, name='interview_bot'),
    
    # Authentications
    path(
        "accounts/login/",
        anonymous_required(
            auth_views.LoginView.as_view(template_name="accounts/login.html")
        ),
        name="login",
    ),
    path(
        "accounts/logout/",
        login_required(
            auth_views.LogoutView.as_view(template_name="accounts/logout.html"),
        ),
        name="logout",
    ),
    path(
        "accounts/register/",
        anonymous_required(views.register),
        name="register",
    ),

    # API
    path("initiate_resume_parsing", api_views.initiate_resume_parsing, name="initiate_resume_parsing"),
    path("interview_bot_starter/", views.interview_bot_starter, name="interview_bot_starter")
]

DevHireExtended/DevHireExtended/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("DevHireBot.urls")),
]

DevHireExtended/DevHireBot/models.py
from django.contrib.auth.models import AbstractUser
from django.core.exceptions import ValidationError
from django.core.validators import FileExtensionValidator
from django.db import models

def validate_file_size(value):
    limit = 5 * 1024 * 1024  # 5 MB in bytes
    if value.size > limit:
        raise ValidationError('File size cannot exceed 5 MB.')

class User(AbstractUser):
    email = models.EmailField(unique=True)
    resume = models.FileField(
        upload_to='resumes/',
        blank=True,
        null=True,
        validators=[
            FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx']),
            validate_file_size
        ]
    )
    
   

DevHireExtended/DevHireBot/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from .models import User, validate_file_size
from django.core.exceptions import ValidationError
from django.core.validators import FileExtensionValidator


class SignUpForm(UserCreationForm):
    first_name = forms.CharField(
        label="First Name",
        widget=forms.TextInput(
            attrs={"class": "px-2 my-1", "placeholder": "Locus"}
        ),
        required=True,  # Set the field as required
    )
    last_name = forms.CharField(
        label="Last Name",
        widget=forms.TextInput(
            attrs={"class": "px-2 my-1", "placeholder": "Focus"}
        ),
        required=True,  # Set the field as required
    )

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        # Add custom classes to the widget attributes for each field
        for field_name in self.fields:
            self.fields[field_name].widget.attrs["class"] = "px-2 my-1"

        self.fields["username"].widget.attrs["placeholder"] = "LocusFocus"
        self.fields["email"].widget.attrs["placeholder"] = "locusfocus@gmail.com"
        self.fields["password1"].widget.attrs["placeholder"] = "abc123"
        self.fields["password2"].widget.attrs[
            "placeholder"
        ] = "abc123 (again)"



    class Meta:
        model = User
        fields = ["first_name", "last_name", "username", "email", "password1", "password2"]

class ResumeForm(forms.Form):
    resume = forms.FileField(
        validators=[
            FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx']),
            validate_file_size
        ]
    )

DevHireExtended/DevHireBot/views.py
import os
from django.shortcuts import render, redirect
from django.contrib import messages
from django.http import HttpResponse, JsonResponse
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate, login, logout
from .forms import SignUpForm, ResumeForm
from django.contrib.auth.decorators import login_required

from . import main
from . import Interview
import json

# Create your views here.
def index(request):
    return render(request, "DevHireBot/index.html")


def register(request):
    if request.method == "POST":
        form = SignUpForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect("DevHireBot:index")
        else:
            messages.error(request, form.errors)
            return render(
                request,
                "accounts/register.html",
                {"form": SignUpForm(request.POST)},
            )
    else:
        if request.user.is_authenticated:
            return redirect("DevHireBot:index")
        else:
            return render(
                request, "accounts/register.html", {"form": SignUpForm()}
            )

@login_required
def get_resume(request):
    if request.method == 'POST':
        form = ResumeForm(request.POST, request.FILES)
        if form.is_valid():
            uploaded_file = request.FILES['resume']
            user = request.user

            if user.resume:
                # Delete the old resume file if it exists
                user.resume.delete()

            user.resume = uploaded_file
            user.save()

            return redirect('DevHireBot:interview_pilot')
        else:
            messages.error(request, form.errors)
    
    else:  # GET request
        form_data = {'resume': request.user.resume} if request.user.resume else None
        form = ResumeForm(initial=form_data)

    return render(request, "DevHireBot/data.html", {'form': form, 'resume_name': os.path.basename(request.user.resume.name) if request.user.resume else None})

@login_required
def interview_pilot(request):
    if not request.user.resume:
        return redirect("DevHireBot:get_resume")
        
    return render(request, "DevHireBot/interview_pilot.html")

@login_required
def interview_bot(request):
    if not request.user.resume:
        return redirect("DevHireBot:get_resume")
    
    return render(request, "DevHireBot/interview_bot.html")

@login_required
def interview_bot_starter(request):
    if request.method == "POST" or request.method == "GET":
        if not request.user.resume:
            return JsonResponse({"result": False})

        json_stuff = request.body
        json_string = json_stuff.decode('utf-8')
        print("JSON String:", json_string)

        data = json.loads(request.body)  # Parse the JSON data sent in the request body
        prompt = data.get("prompt")

        if data.get("fname"):
            resume_json_filePath = request.session.get('resume_json_filePath') # Retrieve the stored filename from the session
        
            if resume_json_filePath:
                with open(resume_json_filePath, 'r') as json_file:
                    json_data = json.load(json_file)
                botResponse = Interview.interview_go(request,json_data)
                print(type(botResponse),botResponse)
                return JsonResponse({"result":botResponse})
            else:
                return JsonResponse({"result": False, "error": "Filename not found in session"})
        
        else:
            botResponse = Interview.interview_process(request,prompt)
            return JsonResponse({"ans":botResponse})

    else:
        return JsonResponse({'error': 'Invalid request method'}, status=405)

DevHireExtended/DevHireBot/templates/DevHireBot/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>
      {% block title %}
        DevHireExtended
      {% endblock %}
    </title>
    <!-- CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9" crossorigin="anonymous" />
    <!-- JavaScript -->
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.min.js" integrity="sha384-Rx+T1VzGupg4BHQYs2gCW9It+akI2MM/mndMCy36UVfodzcJcF0GGLxZIzObiEfa" crossorigin="anonymous"></script>
    <!-- Icons -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css" />
    <!-- Favicon -->
    <link rel="icon" type="image/x-icon" href="{% static 'DevHireBot/favicon/favicon - Icon.ico' %}">
    <!-- Personal -->
    <link href="{% static 'DevHireBot/base.css' %}" rel="stylesheet">

    {% block extraHeader %}
    {% endblock %}
  </head>
  <body>

    <!-- Navbar -->
    <div class="container-fluid dark-hf">
        <nav class="navbar navbar-expand-lg bg-body-tertiary container-xxl">
            <div class="container-fluid" style="color: white;">
            <a class="navbar-brand fs-2" href="{% url 'DevHireBot:index' %}">DevHire - Extended</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
              <i class="bi bi-list"></i>
            </button>
            <div class="collapse navbar-collapse justify-content-end fs-6" id="navbarSupportedContent">
                <ul class="navbar-nav mb-2 mb-lg-0">
                    <li class="nav-item text-center mx-2">
                        <a class="nav-link" aria-current="page" href="{% url 'DevHireBot:index' %}">Home</a>
                    </li>
                    <li class="nav-item text-center mx-2">
                        <a class="nav-link" href="#">Team</a>
                    </li>
                    <li class="nav-item text-center mx-2 btn2 px-3 rounded">
                        {% if user.is_authenticated %}
                        <a class="nav-link" href="{% url 'DevHireBot:logout' %}">Logout</a>
                        {% else %}
                        <a class="nav-link" href="{% url 'DevHireBot:login' %}">Login</a>                    
                        {% endif %}
                    </li>
                </ul>
            </div>
            </div>
        </nav>
    </div>

    <!-- Body -->
    <div class="container-xxl body-d">
      {% block body %}
      {% endblock %}
    </div>
  
    <!-- Footer -->
    <footer class="bd-footer bg-body-tertiary dark-background border-top py-3 mt-5">
        <div class="text-center" style="font-size: 0.9rem;">DevHire Extended is a project by <span class="fw-semibold">Prometheus</span></div>
    </footer>
</body>
</html>

DevHireExtended/DevHireBot/templates/DevHireBot/data.html
{% extends 'DevHireBot/base.html' %}
{% load static %}

{% block body %}
<div class="container-fluid dd1 py-3 px-2 mt-5 mb-3">
        
    <div class="row justify-content-between">

        <div class="left-panel col py-3 px-4 my-3">

            <div class="display-6 mb-4 px-2 fw-medium">Your Profile Details</div>
            <div class="mb-4">📋 Here's a quick overview of your profile information. Keep your details up-to-date to ensure a seamless experience on our platform.</div>
            
            <table class="table table-borderless mb-4">
                <tbody>
                <tr>
                    <th scope="row">First Name</th>
                    <td>{{ user.first_name }}</td>
                </tr>
                <tr>
                    <th scope="row">Last Name</th>
                    <td>{{ user.last_name }}</td>
                </tr>
                <tr>
                    <th scope="row">Email</th>
                    <td>{{ user.email }}</td>
                </tr>
                <tr>
                    <th scope="row">Resume</th>
                    <td id="resume_name">
                        {% if user.resume %}
                        {{ resume_name }}
                        {% else %}
                            ...(*￣０￣)ノ You got no resume bro!!!
                        {% endif %}
                    </td>
                </tr>
                </tbody>
            </table>

            {% if user.resume %}
            <div class="mt-3" style="font-size: 0.8rem">
                Welcome back! 🎉 We still have your previously submitted resume on file. <br>Proceed with your existing resume. Just click the button below to start your interview.
            </div>
            <div class="d-flex align-items-center p-1 mx-3 mt-3 initiate-d" style="border-bottom: 3px solid #692ED0; width: 13rem;">
                <a href="{% url 'DevHireBot:interview_pilot' %}"><button class="rounded my-2" style="border: none; outline: none; background-color: transparent; color: white; font-weight: 600;" >Initiate Interview</button></a>
                <script src="https://cdn.lordicon.com/bhenfmcm.js"></script>
                <lord-icon
                    src="https://cdn.lordicon.com/zmkotitn.json"
                    trigger="hover"
                    colors="primary:#fff"
                    state="hover-1"
                    target=".initiate-d"
                    style="width:3em;height:2em">
                </lord-icon>
            </div>
            
            <div class="my-5 position-relative">
                <hr>
                <span class="fs-5 or1 text-center">OR</span>
            </div>
            
            <div class="mt-3 mb-4" style="font-size: 0.8rem">
                Provide a new or updated resume for a fresh start. This will replace your previous submission and help us tailor your interview experience better.
            </div>

            {% else %}
            <div class="mt-3 mb-4" style="font-size: 0.8rem">
                🌟 Ready to shine? Share your journey with us by submitting your resume! 📄💼
            </div>
            {% endif %}

            <form class="mx-1" action="{% url 'DevHireBot:get_resume' %}" method="post" enctype="multipart/form-data">
                {% csrf_token %}
                <div class="row align-items-center mt-3">
                    <div class="UploadResume d-flex justify-content-center align-items-center">
                        <script src="https://cdn.lordicon.com/bhenfmcm.js"></script>
                        <lord-icon
                            src="https://cdn.lordicon.com/wfadduyp.json"
                            trigger="morph"
                            target=".UploadResume"
                            colors="primary:#fff"
                            state="hover-1"
                            style="width:2.5rem;height:2.5rem; margin-right: 5px;">
                        </lord-icon> 
                        <input type="file" name="resume" autofocus='false' required id="id_resume">
                        <span>Upload Resume</span> 

                        <script>
                            const customFileUpload = document.querySelector('.UploadResume');
                            const fileInput = document.getElementById('id_resume');
                            const fileNameSpan = document.getElementById('resume_name');
                        
                            customFileUpload.addEventListener('click', () => {
                                fileInput.click(); // Trigger the file input's click event
                            });
                        
                            fileInput.addEventListener('change', () => {
                                if (fileInput.files.length > 0) {
                                    fileNameSpan.textContent = fileInput.files[0].name;
                                    customFileUpload.style.backgroundColor = '#692ED0'; // Keep button colored
                                }
                            });
                        </script> 

                        
                    </div>
                    <div class="d-flex align-items-center p-1 mx-3 mt-2 initiate-d" style="border-bottom: 3px solid #692ED0; width: 13rem;">
                        <input type="submit" id="Initiatebtn" class="rounded my-2" value="Initiate Interview">
                        <script src="https://cdn.lordicon.com/bhenfmcm.js"></script>
                        <lord-icon
                            src="https://cdn.lordicon.com/zmkotitn.json"
                            trigger="hover"
                            colors="primary:#fff"
                            state="hover-1"
                            target=".initiate-d"
                            style="width:3em;height:2em">
                        </lord-icon>
                    
                    </div>
                </div>
                
            </form>

            {% if messages %}
            <div class="alert alert-warning mt-4" style="font-size: 0.8rem;" role="alert">
                {% for message in messages %}
                    {{ message }}
                {% endfor %}
            </div>
            {% endif %}
        </div>

        <div class="right-panel col-12 col-lg-6 d-flex flex-column align-items-center px-5 rounded" style="background-color: #181818; height: max-content;">
            <img src="{% static 'DevHireBot/resume.png' %}" alt="envelope picture" style="width: 15rem;">
            <div class="fs-5">Crafting an Impressive Resume: 🚀 Your Path to Professional Success</div>
            <div style="font-size: 0.9rem;">
            <ol class="list-group list-group-numbered">
                <li class="list-group-item d-flex justify-content-between align-items-start">
                    <div class="ms-2 me-auto">
                    <div class="fw-bold">First Impressions Matter</div>
                    🌟  Your resume is an introduction to employers. Make it impactful to set the tone.
                    </div>
                </li>
                <li class="list-group-item d-flex justify-content-between align-items-start">
                    <div class="ms-2 me-auto">
                    <div class="fw-bold">Showcasing Your Achievements</div>
                    🏆  Highlight past successes to demonstrate your value. Use numbers to quantify impact.
                    </div>
                </li>
                <li class="list-group-item d-flex justify-content-between align-items-start">
                    <div class="ms-2 me-auto">
                    <div class="fw-bold">Clear and Concise Communication</div>
                    ✍️ Present your qualifications clearly. Hiring managers appreciate brevity.
                    </div>
                </li>
                <li class="list-group-item d-flex justify-content-between align-items-start">
                    <div class="ms-2 me-auto">
                    <div class="fw-bold">Tailored for the Role</div>
                    🎯 Tailor your resume to each job. Highlight skills, experience, and keywords.
                    </div>
                </li>
                </ol>
            </div>
        </div>

    </div>

</div>
{% endblock body %}

DevHireExtended/DevHireBot/templates/DevHireBot/index.html
{% extends 'DevHireBot/base.html' %}
{% load static %}

{% block body %}
    <div class="container-fluid dd1 py-3 px-2 mt-5 mb-3">
        
        <div class="left-panel col-lg-5 col-12 p-3">

            <div class="display-6 mb-5 px-2 fw-medium">Elevate Interview Success: Beyond Expectations 🚀</div>
            <div class="fw-light fs-6 px-2">
                Welcome to DevHire Extended, your gateway to interview excellence and career triumphs. 🌟 We're not just another platform; we're your personal interview transformation partner, ready to propel you to new heights of success.
            </div>
            <script src="https://cdn.lordicon.com/bhenfmcm.js"></script>

            <a href="{% url 'DevHireBot:get_resume' %}">
                <button class="fw-light btn1 py-2 px-3 my-3">
                    <span>Start your Interview </span>
                    <lord-icon
                        src="https://cdn.lordicon.com/zmkotitn.json"
                        trigger="hover"
                        colors="primary:#fff"
                        state="hover-2"
                        target=".btn1"
                        style="width:3em;height:2em;">
                    </lord-icon>
                </button>
            </a>
        </div>

        <div class="right-panel col d-lg-block d-none">
            <script type="module" src="https://unpkg.com/@splinetool/viewer@0.9.425/build/spline-viewer.js"></script>
            <spline-viewer loading-anim url="https://prod.spline.design/c2iKbmIevkPn-rf1/scene.splinecode"></spline-viewer>
            <div class="hidelogo"></div>
        </div>
    </div>
{% endblock body %}

DevHireExtended/DevHireBot/templates/DevHireBot/interview.html
{% extends 'DevHireBot/base.html' %}
{% load static %}

{% block body %}
<div class="container-fluid dd1 flex-column py-3 px-2 mt-5 mb-3">
    
    <div class='display-3'>PDF has been saved.</div>
    <div class='lead'>
        From this point, we will read the file and start the interview.
    </div>
    <div class='lead mt-5'>
        TO BE DONE SOON (～￣▽￣)～
    </div>

</div>
{% endblock body %}

DevHireExtended/DevHireBot/templates/DevHireBot/interview_pilot.html
{% extends 'DevHireBot/base.html' %}
{% load static %}

{% block body %}
  <div id="interview-pilot-d" class="container-xxl flex-column py-3 px-2 mb-3">
    <div class="d-flex align-items-center justify-content-center flex-column col-12 p-3 mt-5">
      <div class="d-flex justify-content-center">
        <div class="spinner-border" style="width: 3rem; height: 3rem;" role="status">
          <span class="visually-hidden">Loading...</span>
        </div>
      </div>
      <div id="loading_text" class="mt-4 fs-4" style="height: 2.6rem;">Extracting candidate's education details...</div>
      <script>
        const loadingText = document.getElementById("loading_text");
        const extractionSteps = [
        "Analyzing work experience...",
        "Processing project information...",
        "Identifying known programming languages...",
        "Detecting candidate's interests...",
        "Evaluating technical skills...",
        "Verifying professional certifications...",
        "Checking for awards and achievements...",
        ];


        function typing(loadingLine) {
        let i = 0;
        const interval = setInterval(() => {
            if (i < loadingLine.length) {
              loadingText.textContent += loadingLine.charAt(i); //type each letter of the string one by one
              i++;
            } else {
              clearInterval(interval);
            }
          }, 70);
          return interval;
        }

        let stepIndex = 0;
        let currentInterval;

        function changeLineWithDelay() {
          if (currentInterval) {
            clearInterval(currentInterval);
          }

          loadingText.textContent = ""; //initialize the loading text
          var loadingLine = extractionSteps[stepIndex];
          currentInterval = typing(loadingLine);

          const typingDuration = loadingLine.length * 50;
          const nextChangeDelay = typingDuration + 800;

          setTimeout(changeLineWithDelay, nextChangeDelay);
          stepIndex = (stepIndex + 1) % extractionSteps.length;
        }

        changeLineWithDelay(); // Start the initial line change
      </script>
    </div>
  </div>
  <script>
    document.addEventListener("DOMContentLoaded", () => {
        // Replace 'YOUR_ENDPOINT_URL' with the actual URL for the API endpoint
        let endpointUrl = '{% url "DevHireBot:initiate_resume_parsing" %}';
        
        console.log("Initiating Pilot");
        fetch(endpointUrl, {
          method: 'GET',
        })
        .then(response => {
          if (response.status === 204) {
            let myDiv = document.querySelector("#interview-pilot-d");
            myDiv.innerHTML = `
            <div class="p-2">
              <div class='fs-4 text-center'>🤖 Uh-Oh, Something Went Wrong 🤖😟</div>
              <div class='mt-2 lead text-center'>Oops! It looks like things didn't quite go as planned.  (。<span style="color: #692ED0">_</span>。)</div>
            </div>
              `;
            return null;
          }
          return response.json();
        })
        .then(data => {
          if (data) {
            let newPage = '{% url "DevHireBot:interview_bot" %}';
              window.location.href = newPage;
          }
        });
    });
  </script>
{% endblock %}

DevHireExtended/DevHireBot/templates/accounts/login.html
{% extends 'DevHireBot/base.html' %}
{% load static %}

{% block body %}
    <div class="d-flex flex-column justify-content-center align-items-center col-9 col-md-6 col-lg-5 border border-secondary-subtle rounded dd2 px-1 py-4 mx-auto my-5">
        <div class="fs-1 mt-1 mb-4">Login</div>

        <form action="{% url 'DevHireBot:login' %}" method="post" class="col-10">
            {% csrf_token %}
            <div class="input-d col-12 mb-4">
                <label class="mb-1 fs-5" for="id_username">Username:</label>
                <input type="text" class="px-2 my-1" name="username" autofocus autocapitalize="none" autocomplete="username" maxlength="150" required id="id_username" placeholder="Locus Focus">
            </div>
            
            <div class="input-d col-12 mb-4">
                <label class="mb-1 fs-5" for="id_password">Password:</label>
                <input type="password" class="px-2 my-1" name="password" autocomplete="current-password" required id="id_password" placeholder="abc123">
            </div>
            
            {% if form.errors %}
                <div class="alert alert-danger" style="font-size: 0.8em;" role="alert">
                <p>Oops! There was an issue:</p>
                <ul>
                    {% for field, errors in form.errors.items %}
                    {% for error in errors %}
                        <li>{{ field }}: {{ error }}</li>
                    {% endfor %}
                    {% endfor %}
                </ul>
                </div>
            {% endif %}

            <input type="submit" class="btn2 col-12 px-4 py-2 mt-4 mb-2 rounded fs-5" value="Login">
            <div class="mt-2" style="font-size: 0.9em;">New here? <a href="{% url 'DevHireBot:register' %}"><span class="mt-4 mb-3 link1">Create an account </span></a>and join us! 🌟</div>
        </form>
    </div>
{% endblock body %}

DevHireExtended/DevHireBot/templates/accounts/logout.html
{% extends 'DevHireBot/base.html' %}
{% load static %}

{% block body %}
    
    <div class="col-8 border border-secondary-subtle rounded dd2 px-5 py-4 mx-auto my-5">
        <div class="fs-3 mt-1 mb-4">You're all logged out. 😊</div>
        <div class="lead mt-1 mb-3">Thanks for spending valuable time on the website today! 🌟</div>
        <a href="{% url 'DevHireBot:login' %}"><div class="mt-4 mb-3 link1">Log in again</div></a>
    </div>

{% endblock body %}

DevHireExtended/DevHireBot/templates/accounts/register.html
{% extends 'DevHireBot/base.html' %}
{% load static %}

{% block body %}
    <div class="d-flex flex-column justify-content-center align-items-center col-9 col-md-6 border border-secondary-subtle rounded dd2 px-4 py-4 mx-auto my-5">
        <div class="fs-1 mt-1 mb-4">Register</div>
        <form action="{% url 'DevHireBot:register' %}" method="post" class="col-12">
            {% csrf_token %}
            <div class="input-d col-12 mb-4">
                <label class="mb-1 fs-5" for="id_first_name">First Name:</label>             
                {{ form.first_name }}                
            </div>
            <div class="input-d col-12 mb-4">
                <label class="mb-1 fs-5" for="id_last_name">Last Name:</label>             
                {{ form.last_name }}                
            </div>
            <div class="input-d col-12 mb-4">
                <label  class="mb-1 fs-5" for="id_username">Username:</label>
                {{ form.username }}  
                <div class="col-10 px-2 mt-2" style="font-size: 0.7em;">
                    Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.
                </div>              
            </div>
            <div class="input-d col-12 mb-4">
                <label class="mb-1 fs-5" for="id_email">Email address:</label>
                {{ form.email }}                
            </div>
            <div class="input-d col-12 mb-4">
                <label class="mb-1 fs-5" for="id_password1">Password:</label>
                {{ form.password1 }}                
                <div class="col-10 px-2 mt-2" style="font-size: 0.7em;">
                    <ul class="mt-2">
                        <li>Your password can’t be too similar to your other personal information.</li>
                        <li>Your password must contain at least 8 characters.</li>
                        <li>Your password can’t be a commonly used password.</li>
                        <li>Your password can’t be entirely numeric.</li>
                    </ul>
                </div>
            </div>
            <div class="input-d col-12 mb-4">
                <label class="mb-1 fs-5" for="id_password2">Password confirmation:</label>
                {{ form.password2 }}
                <div class="col-10 px-2 mt-2" style="font-size: 0.7em;">
                    Enter the same password as before, for verification.
                </div>                
            </div>
             
            <input type="submit" class="btn2 col-12 px-4 py-2 mt-4 mb-2 rounded fs-5" value="Sign Up">
            
            {% if messages %}
                {% for message in  messages%}
                <div class="dd3" style="border: none; font-size: 0.8rem;">
                    <div class="alert alert-warning" role="alert">
                        {{ message }}
                    </div>
                </div>
                {% endfor %}
            {% endif %}
            
            <div class="mt-2" style="font-size: 0.9em;">Are we acquainted? You can  <a href="{% url 'DevHireBot:login' %}"><span class="mt-4 mb-3 link1">Login here </span></a></div>
        </form>
    </div>
{% endblock body %}